apiVersion: v1
kind: Service
metadata: {annotations: null, name: summitag-primary, namespace: summitag}
spec:
  ports:
  - {name: tds, port: 1433, targetPort: 1433}
  selector: {role.ag.mssql.microsoft.com/summitag: primary, type: sqlservr}
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata: {annotations: null, name: summitag-secondary, namespace: summitag}
spec:
  ports:
  - {name: tds, port: 1433}
  selector: {role.ag.mssql.microsoft.com/summitag: secondary,
    type: sqlservr}
  type: LoadBalancer
---