version: 2.0
services:
  mssql: 
    image: ericskang/unittestdb:latest
    container_name: mssql
    ports:
      - "1433:1433"
    environment: 
      SA_PASSWORD: "!test123"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
  webapp:
    image: ericskang/webapp:latest
    depends on: 
      - mssql
    container_name: webapp
    ports: 
      - "80:3000" 